server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: 1234
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: GMT+7

# app properties
cloudinary:
  name: dixswfj8d
  apiKey: 876943471796471
  apiSecret: XXlwrvw541Qmp83wIgDjxZpIoNQ
  rootFolder: quiz-website-images
jwt:
  jwtSecret: ======================jwt=spring===========================
  jwtExpiration: 10 hour
  jwtRefreshExpiration: 15 hour